version: '3.8'

services:
  web:
    image: python:3.11-slim
    container_name: python_app
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
