version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    

  node-app:
    restart: always
    build: .
    container_name: node    
    ports:
      - 8080:8080
    depends_on:
      - redis
    


  
    