
---

### 6. **Docker Compose with Service Dependencies and Delayed Start (Ruby on Rails + Redis + PostgreSQL)**

# This setup demonstrates a Ruby on Rails application connected to both Redis and PostgreSQL with service dependencies and delayed start to ensure correct startup order.

# ```yaml
version: '3.8'

services:
  web:
    image: ruby:3.2-alpine
    container_name: rails_app
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "sleep 10 && rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: rails_db
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  pg_data:
