
---

### 3. **Reverse Proxy with NGINX + Load-Balanced Services**

# This setup demonstrates using NGINX as a reverse proxy with load balancing between multiple application instances.

# ```yaml
version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    image: node:20-alpine
    container_name: node_app
    volumes:
      - ./app:/app
    working_dir: /app
    command: npm start
    deploy:
      replicas: 3

